#docker-compose.ymlのバージョン
version: '3.8'
#docker volumeの設定
volumes:
  docker-volume:

#services以下に各コンテナの設定を書く

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
    - '443:443'
    restart: always
    environment:
      DOMAINS: 'dlgate-jp.cyou -> web'
      #domainを記述
      STAGE: 'staging'
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal
    depends_on:
      - app
      - web


      #Webサーバーのコンテナ
  web:
    image: nginx:1.18
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  #アプリケーションのコンテナ
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  #データベースのコンテナ
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: Gate
      MYSQL_USER:  yamashiro
      MYSQL_PASSWORD: kazuma115
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - docker-volume:/var/lib/mysql
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION

  test-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: laravel_test
    ports: 
      - 3307:3306