#docker-compose.ymlのバージョン
version: '3.8'
#docker volumeの設定
volumes:
  docker-volume:

#services以下に各コンテナの設定を書く
# services:

#   proxy:
#     build: ./proxy
#     tty: true
#     image: proxy
#     container_name: proxy
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"
#     ports:
#       - "443:443"
#     volumes:
#       - '/srv/letsencrypt:/etc/letsencrypt'
#     networks:
#       - default
#       - proxy_nw
#     depends_on:
#       - "web1"
#       - "web2"
#     command: ["wait-for-it.sh", "web1:80", "--", "./wait-for-it.sh", "web2:80"]

#   web1:
#     image: httpd
#     container_name: web1
#     tty: true
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"
#     networks:
#       - proxy_nw
#   web2:
#     image: httpd
#     container_name: web2
#     tty: true
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"
#     networks:
#       - proxy_nw
# networks:
#   proxy_nw:
#     external: true





  #Webサーバーのコンテナ
  web:
    image: nginx:1.18
    environment:
      PORT: 80
      HOST: 0.0.0.0
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  #アプリケーションのコンテナ
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  #データベースのコンテナ
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: Gate
      MYSQL_USER:  yamashiro
      MYSQL_PASSWORD: kazuma115
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - docker-volume:/var/lib/mysql
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION

  test-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: laravel_test
    ports: 
      - 3307:3306